"""Import public/logos into the Terraform-managed Sponsors table.

Dry-run by default; --execute inserts only missing images and preserves edits.
IDs are autogenerated stable UUIDs, so retries never create duplicate sponsors.
"""
import argparse
import json
import os
from pathlib import Path
from uuid import NAMESPACE_URL, uuid5

ROOT = Path(__file__).resolve().parents[2]
COLUMNS = {'id': 'Utf8', 'name': 'Utf8', 'image': 'Utf8', 'link': 'Utf8', 'display': 'Bool'}


def seed_rows(directory):
    images = sorted(path for path in directory.iterdir()
                    if path.is_file() and not path.name.startswith('.')
                    and path.suffix.lower() in {'.jpg', '.jpeg', '.png', '.webp', '.svg'})
    if not images:
        raise ValueError('No sponsor images found')
    return [dict(id=str(uuid5(NAMESPACE_URL, 'festival-mental-health:sponsor:logos/' + path.name)),
                 name='', image='logos/' + path.name, link='', display=True) for path in images]


def missing_rows(seeds, existing):
    by_image = {row['image']: row for row in existing}
    if len(by_image) != len(existing):
        raise ValueError('Duplicate Sponsors.image values; reconcile before importing')
    by_id = {row['id']: row for row in existing}
    additions = []
    for row in seeds:
        if row['image'] in by_image:
            continue
        if row['id'] in by_id:
            raise ValueError('Generated sponsor ID belongs to a different image')
        additions.append(row)
    return additions


def read_rows(session, tx):
    result = tx.execute(session.prepare('SELECT id, name, image, link, display FROM Sponsors ORDER BY image, id;'))
    if len(result) != 1 or result[0].truncated:
        raise ValueError('Incomplete Sponsors read')
    return [dict(row) for row in result[0].rows]


def import_rows(session, seeds, execute=False):
    import ydb
    with session.transaction(ydb.SerializableReadWrite()) as tx:
        before = read_rows(session, tx)
        additions = missing_rows(seeds, before)
        if execute and additions:
            declarations = ' '.join(f'DECLARE ${key} AS {kind};' for key, kind in COLUMNS.items())
            query = session.prepare(declarations +
                ' INSERT INTO Sponsors (id, name, image, link, display) VALUES ($id, $name, $image, $link, $display);')
            for row in additions:
                tx.execute(query, {'$' + key: value for key, value in row.items()})
            after = read_rows(session, tx)
            expected = {row['id']: row for row in before + additions}
            if {row['id']: row for row in after} != expected:
                raise ValueError('Sponsors read-back mismatch')
        tx.commit()
        return {'existing': len(before), 'added' if execute else 'to_add': len(additions),
                'images': len(seeds)}


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--execute', action='store_true')
    args = parser.parse_args()
    seeds = seed_rows(ROOT / 'public/logos')
    import ydb
    import ydb.iam
    with ydb.Driver(endpoint=os.environ['YDB_ENDPOINT'], database=os.environ['YDB_DATABASE'],
                    credentials=ydb.iam.ServiceAccountCredentials.from_file(os.environ['YC_SERVICE_ACCOUNT_KEY_FILE'])) as driver:
        driver.wait(timeout=30, fail_fast=True)
        with ydb.SessionPool(driver, size=1) as pool:
            def apply(session):
                columns = {column.name: str(column.type) for column in session.describe_table(os.environ['YDB_DATABASE'].rstrip('/') + '/Sponsors').columns}
                if columns != COLUMNS:
                    raise ValueError('Sponsors schema differs from the expected five non-null columns')
                return import_rows(session, seeds, args.execute)
            print(json.dumps(pool.retry_operation_sync(apply)))


if __name__ == '__main__':
    main()
